#include <errno.h>

#define ERR_ITEM(error_code) { error_code, #error_code }

struct error_table
{
	int code;
	char str[16];
} err_tbl[] = {
	ERR_ITEM(EPERM),
	ERR_ITEM(ENOENT),
	ERR_ITEM(ESRCH),
	ERR_ITEM(EINTR),
	ERR_ITEM(EIO),
	ERR_ITEM(ENXIO),
	ERR_ITEM(E2BIG),
	ERR_ITEM(ENOEXEC),
	ERR_ITEM(EBADF),
	ERR_ITEM(ECHILD),
	ERR_ITEM(EAGAIN),
	ERR_ITEM(ENOMEM),
	ERR_ITEM(EACCES),
	ERR_ITEM(EFAULT),
	ERR_ITEM(ENOTBLK),
	ERR_ITEM(EBUSY),
	ERR_ITEM(EEXIST),
	ERR_ITEM(EXDEV),
	ERR_ITEM(ENODEV),
	ERR_ITEM(ENOTDIR),
	ERR_ITEM(EISDIR),
	ERR_ITEM(EINVAL),
	ERR_ITEM(ENFILE),
	ERR_ITEM(EMFILE),
	ERR_ITEM(ENOTTY),
	ERR_ITEM(ETXTBSY),
	ERR_ITEM(EFBIG),
	ERR_ITEM(ENOSPC),
	ERR_ITEM(ESPIPE),
	ERR_ITEM(EROFS),
	ERR_ITEM(EMLINK),
	ERR_ITEM(EPIPE),
	ERR_ITEM(EDOM),
	ERR_ITEM(ERANGE)
};
